### ISSUE TITLE
Disable colors when stdout is not a tty

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/pogrep#52]
Typical usage:

    emacs $(pogrep --translation --no-source -r mapping -l)

for the moment I need to use:

    emacs $(pogrep --translation --no-source -r mapping -l | ansi2txt | sed s/B$//)

**Comment by christopheNan** [comment]
Indeed, the *pogrep* implementation does not use *GREP_COLORS* as defined in ``man grep``. The first step may be to comply with *GREP_COLORS*.

**Comment by JulienPalard** [comment]
Released as 0.1.3.
